import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";

const libre_franklin = Libre_Franklin({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "youandme",
  description: "Generated by Jirawad SAU",
  keywords: ["youandme", "ตัวเอง","แนะนำ",],
  icons: {
    icon: "/vercal.svg"
  },
  authors: [{
    name: "Jirawad",
    url: "https://jirawadeiei.com"
  }]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libre_franklin.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
